In [0]:
import numpy as np
import random
import gym

In [0]:
# Create env
env = gym.make("FrozenLake-v0")

# You want to start at S 
# Target is G
# Avoid oles H
# If you take one step continuously and stuck into one position then 
# env will shift your position to adjecent any position

In [0]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [31]:

qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
total_episodes = 30000        # Total episodes
learning_rate = 0.2           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.98                  # Discounting rate

# Exploration parameters
epsilon = 0.8                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.01             # Exponential decay rate for exploration prob

In [33]:
# List of rewards
rewards = []

# 2 For life or until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)
        
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()

        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
        
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.6242
[[0.42282633 0.29074647 0.3225403  0.31367734]
 [0.17262763 0.16741883 0.09212149 0.31477508]
 [0.20119323 0.15288477 0.13793895 0.15255964]
 [0.04436536 0.01245344 0.02869127 0.        ]
 [0.43763609 0.27581665 0.28621146 0.28361961]
 [0.         0.         0.         0.        ]
 [0.2340067  0.02263419 0.08684511 0.04264574]
 [0.         0.         0.         0.        ]
 [0.28305487 0.33251005 0.2668489  0.4606578 ]
 [0.31887165 0.48890125 0.32916411 0.23471227]
 [0.53422582 0.29357273 0.31476591 0.17372292]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.12075858 0.42449056 0.5554245  0.41964433]
 [0.57859135 0.8465584  0.53816197 0.55065591]
 [0.         0.         0.         0.        ]]


In [34]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)
    print("Start")
    env.render()

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            print("End")
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
Start

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 33
End
****************************************************
EPISODE  1
Start

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 13
End
****************************************************
EPISODE  2
Start

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 17
End
****************************************************
EPISODE  3
Start

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 77
End
****************************************************
EPISODE  4
Start

SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 13
End


In [35]:
state = env.reset()
done = False
while(not done):
  action = np.argmax(qtable[state, :])
  print("State: {} Action: {}".format(state, action))
  new_state, reward, done, info = env.step(action)
  env.render()
  state = new_state
  

State: 0 Action: 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 0 Action: 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 4 Action: 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 8 Action: 3
  (Up)
SFFF
FHFH
FFFH
HFFG
State: 9 Action: 1
  (Down)
SFFF
FHFH
FFFH
HFFG
State: 13 Action: 2
  (Right)
SFFF
FHFH
FFFH
HFFG
State: 14 Action: 1
  (Down)
SFFF
FHFH
FFFH
HFFG
State: 14 Action: 1
  (Down)
SFFF
FHFH
FFFH
HFFG
State: 13 Action: 2
  (Right)
SFFF
FHFH
FFFH
HFFG
State: 14 Action: 1
  (Down)
SFFF
FHFH
FFFH
HFFG
State: 14 Action: 1
  (Down)
SFFF
FHFH
FFFH
HFFG
