In [0]:
import numpy as np
import random
import gym

In [0]:
# Create env
env = gym.make("FrozenLake-v0")

In [0]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [5]:

qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
total_episodes = 30000        # Total episodes
learning_rate = 0.2           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.98                  # Discounting rate

# Exploration parameters
epsilon = 0.8                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.01             # Exponential decay rate for exploration prob

In [13]:
# List of rewards
rewards = []

# 2 For life or until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)
        
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()

        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
        
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.6541333333333333
[[0.43440939 0.32475161 0.30831649 0.33157468]
 [0.12867293 0.248296   0.15103076 0.35485465]
 [0.19968613 0.20422115 0.21922011 0.28495805]
 [0.1836326  0.20322141 0.19601182 0.26469652]
 [0.46902511 0.29266259 0.26337163 0.29533436]
 [0.         0.         0.         0.        ]
 [0.22542698 0.03803431 0.07883311 0.15449654]
 [0.         0.         0.         0.        ]
 [0.24905057 0.32074269 0.39465575 0.52376481]
 [0.39185225 0.57680355 0.30673179 0.34056001]
 [0.51826085 0.16843955 0.21519783 0.19874065]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.2421905  0.51352581 0.66530603 0.56476653]
 [0.63364047 0.87953631 0.73476691 0.661246  ]
 [0.         0.         0.         0.        ]]


In [21]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)
    print("Start")
    env.render()

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            print("End")
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
Start

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 12
End
****************************************************
EPISODE  1
Start

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 91
End
****************************************************
EPISODE  2
Start

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 23
End
****************************************************
EPISODE  3
Start

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 28
End
****************************************************
EPISODE  4
Start

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 12
End


In [20]:
state = env.reset()
done = False
while(not done):
  action = np.argmax(qtable[state, :])
  print("State: {} Action: {}".format(state, action))
  new_state, reward, done, info = env.step(action)
  env.render()
  state = new_state
  

State: 0 Action: 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 4 Action: 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 8 Action: 3
  (Up)
SFFF
FHFH
FFFH
HFFG
State: 8 Action: 3
  (Up)
SFFF
FHFH
FFFH
HFFG
State: 8 Action: 3
  (Up)
SFFF
FHFH
FFFH
HFFG
State: 8 Action: 3
  (Up)
SFFF
FHFH
FFFH
HFFG
State: 9 Action: 1
  (Down)
SFFF
FHFH
FFFH
HFFG
State: 10 Action: 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 14 Action: 1
  (Down)
SFFF
FHFH
FFFH
HFFG
State: 13 Action: 2
  (Right)
SFFF
FHFH
FFFH
HFFG
State: 9 Action: 1
  (Down)
SFFF
FHFH
FFFH
HFFG
State: 10 Action: 0
  (Left)
SFFF
FHFH
FFFH
HFFG
State: 14 Action: 1
  (Down)
SFFF
FHFH
FFFH
HFFG
State: 14 Action: 1
  (Down)
SFFF
FHFH
FFFH
HFFG
State: 14 Action: 1
  (Down)
SFFF
FHFH
FFFH
HFFG
